name: Specs in Docker

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build gdal2 image
        run: |
          docker compose version
          docker compose build gdal2
      - name: Run specs
        run: docker compose run --rm gdal2 bundle exec rspec spec --format RSpec::Github::Formatter --format progress
